### ISSUE TITLE
xml2csv mapping issue

### ISSUE THREAD

**Issue by oujisan2236** [onozaty/xml2csv#1]
Good day Have an issue with one of my XML feeds

Not a standard xml its xsi

if i throw them into notepad++ Looks like this

`<ProductDto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><Code>CO-9050074</Code><Title>Corsair LL140 RGB 140mm Dual Light Loop RGB LED PWM 600 - 1300 RPM Cooling Fan — 2 Fan Pack with Lighting Node PRO</Title><Description>Corsair LL140 RGB 140mm Dual Light Loop RGB LED PWM 600 - 1300 RPM Cooling Fan — 2 Fan Pack with Lighting Node PRO</Description><SellingPrice>2000.0000</SellingPrice><OnHand>0</OnHand><ProductLine>Corsair</ProductLine><VendorCode>CO-9050074-WW</VendorCode><UpcBarcode>843591032452</UpcBarcode><Eta/><Status>Active</Status><DateCreated/><DateModified/></ProductDto>`

The xml feed for example is this (for the sake of cost price sharing ive changed the sellingprice amount

```
<ProductDto>
<Code>CO-9050074</Code>
<Title>
Corsair LL140 RGB 140mm Dual Light Loop RGB LED PWM 600 - 1300 RPM Cooling Fan — 2 Fan Pack with Lighting Node PRO
</Title>
<Description>
Corsair LL140 RGB 140mm Dual Light Loop RGB LED PWM 600 - 1300 RPM Cooling Fan — 2 Fan Pack with Lighting Node PRO
</Description>
<SellingPrice>2000.0000</SellingPrice>
<OnHand>0</OnHand>
<ProductLine>Corsair</ProductLine>
<VendorCode>CO-9050074-WW</VendorCode>
<UpcBarcode>843591032452</UpcBarcode>
<Eta/>
<Status>Active</Status>
<DateCreated/>
<DateModified/>
</ProductDto>
```

So i am unsure what the rowspath should be ive tried this but then the csv only has the 3 headers with no info in collums

```
{
    "rowsPath": "//ProductDto",
    "columns": [
        {
            "header": "code",
            "valuePath": "/code"
        },
        {
            "header": "sellingprice",
            "valuePath": "/sellingprice"
        },
        {
            "header": "onhand",
            "valuePath": "/onhand"
        }
    ]
}
```

So would like to know or advise what rowspath should be and or must there be mapping i dont mind mapping the entire xml into csv as im selecting only 2-3 collums when importing their updates on woocommerce.

The command i am using is (on one that works)
xml2csv/xml2csv -i frontosa.xml -m frontosamapping.json -o frontosa.csv

Now frontosamapping.json rowpath is //item which works 100%

if i try without -m gives me this (test in terminal)
```
[f6502669@wp12 ~]$ xml2csv/xml2csv -i frontosa.xml -o frontosatest.csv
xml2csv v1.0.3 (94ea1ba)

Usage: xml2csv [flags]

Flags
  -i, --input string     XML input file path or directory or url
  -m, --mapping string   XML to CSV mapping file path or url
  -o, --output string    CSV output file path
  -b, --bom              CSV with BOM
  -h, --help             Help

```

Unsure if i must give more information.

Regards
Oujisan2236

**Comment by onozaty** [comment]
Hi @oujisan2236 

Does it mean that the whole XML represents one record?
I hadn't envisioned using it this way, but it is not impossible to write it as XPath.

You can match the whole thing by writing `/*`.
Also, the XPath specified in valuePath seems to be wrong. The case does not match.

Can you please try the following?

```json
{
    "rowsPath": "/*",
    "columns": [
        {
            "header": "code",
            "valuePath": "/Code"
        },
        {
            "header": "sellingprice",
            "valuePath": "/SellingPrice"
        },
        {
            "header": "onhand",
            "valuePath": "/OnHand"
        }
    ]
}
```

Thanks.

**Comment by oujisan2236** [comment]
![image](https://user-images.githubusercontent.com/27886201/139577410-625ef451-ae61-44eb-8713-5279c7b1b21e.png)

but if i make it // instead of /
```
{
    "rowsPath": "//*",
    "columns": [
        {
            "header": "code",
            "valuePath": "/Code"
        },
        {
            "header": "sellingprice",
            "valuePath": "/SellingPrice"
        },
        {
            "header": "onhand",
            "valuePath": "/OnHand"
        }
    ]
}
```
![image](https://user-images.githubusercontent.com/27886201/139577486-a6cd3f8b-3b7b-43e9-960f-ec2c0cb08949.png)

Seems to be spacing out or skipping some.
Let me give you the full feed.
but getting somewhere.
https://rctdatafeed.azurewebsites.net/xml/e3effb20-9935-410d-801a-531b0047b150/v1/Products

**Comment by onozaty** [comment]
The reason for the empty line is that we are also matching elements that are not eligible.

For this XML, rowsPath should be `//ProductDto`.

It would be a good idea to check if XPath is able to select the intended elements.
For example, you can check this in Chrome.

![image](https://user-images.githubusercontent.com/47337/139681599-40a7e7fc-55f8-4c38-98f4-09a13e09726f.png)

**Comment by oujisan2236** [comment]
So found this

https://xmltoolbox.appspot.com/xpath_generator.html

Took the basic (single product XML since it's small)
![image](https://user-images.githubusercontent.com/27886201/139963814-4c6a4307-c0e5-4e89-861a-d5f40fe48a4a.png)

Clicking on the sku code and the amount as well as the stock amount gave the path
![image](https://user-images.githubusercontent.com/27886201/139963890-236513f6-e4d2-401b-b015-5361b5de64d3.png)

```
/ProductDto/OnHand/text()
/ProductDto/SellingPrice/text()
/ProductDto/Code/text()
/ProductDto
```

So the Json i test it and got code to work once i managed that i came up with this (forget the `text()`

```
{
    "rowsPath": "//ProductDto",
    "columns": [
        {
            "header": "code",
            "valuePath": "//ProductDto/Code"
        },
        {
            "header": "sellingprice",
            "valuePath": "//ProductDto/SellingPrice"
        },
        {
            "header": "onhand",
            "valuePath": "//ProductDto/OnHand"
        }
    ]
}
```

Also noticed that the Spelling is okay but Capitals are sensitive something my original one didnt have (my fault)

![image](https://user-images.githubusercontent.com/27886201/139964094-e55cc47f-cd2b-4d93-8630-809cf4c32327.png)

I Redacted the pricing by editing the document before screen shot (cost pricing)

Thank you for helping me in the right direction.

I had no real luck with chrome inspector or firefox just threw errors on me but mine didnt look like yours. Eitherway This is sorted I will When possible sponsor your account .

大変助かりました。ありがとうございました。私はあなたにたくさんのコーヒーを借りています

Arigato

**Comment by onozaty** [comment]
I'm glad you solved it.

>  I will When possible sponsor your account .

Thanks.
