### ISSUE TITLE
Killed: 9 on Apple M3 Pro

### ISSUE THREAD

**Issue by chadbr** [onozaty/xml2csv#3]
I get Killed: 9 after a minute or two of processing... 

Any ideas?

Tried a recompile because of this issue - didn't help: https://github.com/golang/go/issues/19734

Tried to renice the process... didn't help.

Tt's a 22gb source file... might be the problem?

**Comment by onozaty** [comment]
I don't have a Mac with me, so I can't confirm that it works, but I will try to build it again with a newer version of Go to try it out.

Thanks.

**Comment by chadbr** [comment]
Sorry - the kill 9 seems to be an out of memory issue... the OS will kill the process to keep the system from running out of memory.
I assumed the parsing was incremental / event driven but it seems to be parsing the whole file via DOM (it's a 20gb table export from SQL Server)...

If that's not the intended use, no worries. I can find another way to do it.

Thanks! Chad

**Comment by onozaty** [comment]
In the current implementation, the entire XML is parsed, and then XPath is used to search. Therefore, large XML cannot be handled.

I would like to consider a way to solve this problem.

Thanks.

**Comment by onozaty** [comment]
Hi @chadbr 

Improved in v1.1.0. Please try it.

Thanks.

**Comment by chadbr** [comment]
@onozaty forgot to check back in - worked like a champ on very very large files. 

Appreciate the work!
